server:
  port: 8781
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8760/eureka/
spring:
  application:
    name: feign
feign:
  hystrix:
    # feign熔断器开关
    enabled: true
